changelog:
  exclude:
    labels:
      - ignore-for-release
      - minor
    authors:
      - mongodb-php-bot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features
      labels:
        - enhancement
    - title: Fixed
      labels:
        - bug
        - fixed
    - title: Other Changes
      labels:
        - "*"
