services:
    app:
        tty: true
        build: .
        working_dir: /var/www/laravel-mongodb
        command: "bash -c 'composer install && composer run test'"
        environment:
            MONGODB_URI: 'mongodb://mongodb/'
        volumes:
            - .:/var/www/laravel-mongodb
        depends_on:
            mongodb:
                condition: service_healthy

    mongodb:
        container_name: mongodb
        image: mongodb/mongodb-atlas-local:latest
        ports:
            - "27017:27017"
        healthcheck:
            test: mongosh --quiet --eval 'db.runCommand("ping").ok'
            interval: 10s
            timeout: 10s
            retries: 5
